### ISSUE TITLE
TG-263 Conventions

### ISSUE THREAD

**Issue by victorgabr** [cutright/DVH-Check#2]
Hello,

It is not a formal issue. But I have implemented a module that follows the TG-263 naming conventions for DVH metrics.

Would you be interested in a pull request for it?

Details at my repository:

[https://github.com/victorgabr/pps/tree/master/pyplanscoring/constraints](https://github.com/victorgabr/pps/tree/master/pyplanscoring/constraints)

I tried fuzzywuzzy before, but I ended up implementing a simple string matcher at:

[line 386](https://github.com/victorgabr/pps/blob/master/pyplanscoring/constraints/metrics.py)

Regards,
Victor

**Comment by cutright** [comment]
Hi Victor, very interesting... let me take some time to look through your code and see how it can fit in.

I also have this problem in my other project [DVH Analytics](https://github.com/cutright/DVH-Analytics). I've been focused on its desktop application re-write (which is almost ready for the public), but maybe your module could be useful there as well.

**Comment by victorgabr** [comment]
I have forked this repository, and I may try to integrate it or create a standalone module for DVH metrics and export and document an external API so that it may work on both projects, the actual code is still coupled to the DVH calculation method implemented on PPS repository.  I have checked your DVH Analytics project. I was working on something similar to a personal project (on hold) that uses Bokeh/JS as frontend and Django/PostgreSQL backend to store DVH calculations as JSON field.

**Comment by cutright** [comment]
Awesome.  That probably would have been better than DVH Analytics relying solely on Bokeh for the frontend. I gave up on purely using Bokeh as a GUI framework for DVH Analytics, it's not meant for such huge layouts.

If you're interested, I can send you an invite to my private DVH Analytics Desktop project using wxPython.  It's already way more robust than the bokeh version.  Fair warning though, plots to show up on Windows yet (a simple fix I think, just need the environment to test it) and I haven't tested on Linux at all yet.

**Comment by victorgabr** [comment]
Yes, I am interested. I only use Linux on my personal computer, and I may test it for you.

**Comment by MohammadSalehi72** [comment]
Hi 
I'm new to python. how can I use DVH-Check through a code? I clone it and install it, but I don't know how to use it.

**Comment by cutright** [comment]
Hi Mohammad, unfortunately this project needs a lot of love.  I made it pretty hastily several months ago and haven't had a chance to keep it up.  The code does work, but some of the interface objects are not updating as expected.  For, example the Calculate DVH button should turn green and indicate which DVH it is calculating.

I have added some information to the readme on the main project page to get you started since your question does not pertain to this issue (TG-263 Conventions).  The readme can be viewed [here](https://github.com/cutright/DVH-Check).

**Comment by MohammadSalehi72** [comment]
Dear Dan,

This is to thank you for devoting your time to answering my questions and helping me. Certainly, that's how you say it. Such tasks require a great deal of time and energy.
I'm so glad that I found this library. I follow the readme guide and work properly. Thank you again. 
It will be my honor to help you in this regard.

**Comment by cutright** [comment]
Per original issue, [DVH Analytics](https://github.com/cutright/DVH-Analytics) is now TG-263 compliant as of v0.7.4.  I plan to implement this project's code into DVHA shortly.
